<?php
/*
 * implementation of hook_menu()
 */

function menu_festival_link_menu(){
    $items['festival'] = array(
        'title' => 'Festival',
        'page callback' => 'menu_festival_link_festival',
        'access callback' => TRUE,
        'type' => MENU_NORMAL_ITEM,
        'menu_name' => 'main-menu',
        'weight' => 10,
    );
    $items['events_all'] = array(
        'title' => 'Events',
        'page callback' => 'menu_festival_link_events_redirect',
        'access callback' => TRUE,
        'type' => MENU_NORMAL_ITEM,
        'menu_name' => 'main-menu',
    );
    
    return $items;
}

function menu_festival_link_festival(){
    /*$nodes = node_load_multiple(array(), array('type' => 'festival'));
    $nid = $nodes[0]->$nid;
    return (print_r($nodes));*/
    $query = new EntityFieldQuery();
    $query->entityCondition('entity_type', 'node')
      ->entityCondition('bundle', 'festival')
      ->fieldOrderBy('field_festival_date', 'value', 'DESC')
      ->pager(1);
    $result = $query->execute();
    foreach($result['node'] as $nid => $useless_variable){
        drupal_goto('node/'. $nid);
    }
}

function menu_festival_link_events_redirect(){
    drupal_goto('events', array('query' => array('tid' => '')));
}

function menu_festival_link_commerce_cart_order_is_cart($order, &$is_cart) {
    $is_cart = FALSE;
    return FALSE;
}

/*function menu_festival_link_commerce_checkout_page_info_alter(&$checkout_pages) {
  $checkout_pages['review']['weight'] = 15;
  ob_start();
  $handle = fopen("a.txt", 'w');
  print_r($checkout_pages);
  fwrite($handle, ob_get_contents());
  ob_end_clean();
}*/

/**
* Implements hook_block_info().
*/
function menu_festival_link_block_info() {
    $blocks['date_filter'] = array(
        'info' => t('Filter by date genre and type'),
        'status' => TRUE,
        'region' => 'content',
        'weight' => 0,
        'visibility' => 1,
    );
    $blocks['tiny_cart'] = array(
        'info' => t('Tiny cart with quantity of goods'),
        'status' => TRUE,
        'region' => 'content',
        'weight' => 0,
        'visibility' => 1,
    );
    return $blocks;
}

/**
* Implements hook_block_view().
*/

function menu_festival_link_block_view($delta = '') {
    switch ($delta) {
        case 'date_filter':
//            $block['subject'] = t('Date filter');
            $block['content'] = menu_festival_link_block_contents($delta);
            return $block;
            break;
        
        case 'tiny_cart':
            $block['content'] = menu_festival_link_block_contents($delta);
            return $block;
            break;
    }
}

/**
* A module-defined block content function.
*/
function menu_festival_link_block_contents($delta) {
    switch ($delta) {
        case 'tiny_cart':
            global $user;
            $quantity = 0;
            $order = commerce_cart_order_load($user->uid);
            if ($order) {
                $wrapper = entity_metadata_wrapper('commerce_order', $order);
                $line_items = $wrapper->commerce_line_items;
                $quantity = commerce_line_items_quantity($line_items, commerce_product_line_item_types());
                $total = commerce_line_items_total($line_items);
                $currency = commerce_currency_load($total['currency_code']);
            }
            $cart_img = '<a href="'. url('', array('query' => array('q' => 'cart'))). '"><img src = "'. base_path() . path_to_theme() . '/images/commerce/tiny-cart.png" /></a>';
            return (string)$quantity. $cart_img;
            break;
        
        case 'date_filter':
            $all = '';
            $all .= '<div class = "type-filter-events-all">';
            $var_array = $_GET;
            $var_array['type'] = 'fest';
            $href_fest = url('', array('query' => $var_array));
            $var_array['type'] = 'non-fest';
            $href_nonfest = url('', array('query' => $var_array));
            $var_array['type'] = 'all';
            $href_all = url('', array('query' => $var_array));
            $all .= '<p class = "filter-button">All</p><a href="'. $href_all. '"><img src="'. base_path() . path_to_theme() . '/images/filters/currentfilter-big.png" /></a>';
            if(isset($_GET['type']) && $_GET['type'] != 'all'){
                $all .= '<div id="filter-ul" class="opened-ul-filter"><ul class="events-filter-ul">';
            }else{
                $all .= '<div id="filter-ul" class="closed-ul-filter"><ul class="events-filter-ul">';
            }
            $addition['href_fest'] = '';
            $addition['href_nonfest'] = '';
            if(isset($_GET['type'])){
                if($_GET['type'] == 'fest'){
                    $addition['href_fest'] = '<img src="'. base_path() . path_to_theme() . '/images/filters/currentfilter-small.png" />';
                }else if($_GET['type'] == 'non-fest'){
                    $addition['href_nonfest'] = '<img src="'. base_path() . path_to_theme() . '/images/filters/currentfilter-small.png" />';
                }
            }
            $all .= '<li><a href="'. $href_fest. '">festival</a>'. $addition['href_fest']. '</li>';
            $all .= '<li><a href="'. $href_nonfest. '">regular</a>'. $addition['href_nonfest']. '</li>';
            $all .= '</ul></div></div>';
            
            $var_array = $_GET;
            $var_array['field_event_date_value']['value']['date'] = '';
            $href_date = url('', array('query' => $var_array));
            if(isset($_GET['field_event_date_value']['value']['date']) && $_GET['field_event_date_value']['value']['date'] != ''){
                $all .= '<div class = "date-filter-events-all"><p class="filter-button">Date</p><a href="'. $href_date. '"><img src="'. base_path() . path_to_theme() . '/images/filters/currentfilter-big.png" /></a><div id="filter-ul" class="opened-ul-filter"><ul class="events-filter-ul">';
            }else{
                $all .= '<div class = "date-filter-events-all"><p class="filter-button">Date</p><a href="'. $href_date. '"><img src="'. base_path() . path_to_theme() . '/images/filters/currentfilter-big.png" /></a><div id="filter-ul" class="closed-ul-filter"><ul class="events-filter-ul">';
            }
            for($i = 0; $i < 6; $i++){
                $timer = $i == 0 ? date('Y-m-d') : date('Y-m-01', strtotime('+'. $i. ' month'));
                $date_explode = explode('-', $timer);
                $monthName = date("F", mktime(0, 0, 0, $date_explode[1], 10));
                $var_array['field_event_date_value']['value']['date'] = $timer;
                $href_date = url('', array('query' => $var_array));
                $all .= '<li><a href="'. $href_date. '">'. $monthName. '</a>';
                if(isset($_GET['field_event_date_value']['value']['date'])){
                    if($_GET['field_event_date_value']['value']['date'] == $timer){
                        $all .= '<img src="'. base_path() . path_to_theme() . '/images/filters/currentfilter-small.png" />';
                    }
                }
                $all .= '</li>'; 
            }
            $all .= '</ul></div></div>';
            
            
            $vocabularys = taxonomy_get_vocabularies();
            foreach($vocabularys as $tid => $vocabulary){
                if($vocabulary->name == 'genre'){
                    $tags = taxonomy_get_tree($vocabulary->vid);
                    $var_array = $_GET;
                    $var_array['tid'] = '';
                    $href_tax = url('', array('query' => $var_array));
                    $all .= '<div class = "tax-filter-events-all"><p class = "filter-button">Genre</p><a href="'. $href_tax. '"><img src="'. base_path() . path_to_theme() . '/images/filters/currentfilter-big.png" /></a>';
                    if(isset($_GET['tid']) && $_GET['tid'] != ''){
                        $all .= '<div id="filter-ul" class="opened-ul-filter"><ul class="events-filter-ul">';
                    }else{
                        $all .= '<div id="filter-ul" class="closed-ul-filter"><ul class="events-filter-ul">';
                    }
                    foreach($tags as $tag){
                        //$term = str_replace(' ', '+', $tag->name);
                        $var_array['tid'] = $tag->name;
                        $href_tax = url('', array('query' => $var_array));
                        $all .= '<li><a href="'. $href_tax. '">'. $tag->name. '</a>';

                        if(isset($_GET['tid'])){
                            if($_GET['tid'] == $tag->name){
                                $all .= '<img src="'. base_path() . path_to_theme() . '/images/filters/currentfilter-small.png" />';
                            }
                        }
                        $all .= '</li>';
                    }
                    $all .= '</ul></div></div>';
                }
            }
            return $all;
            /*$view = views_get_view('events');
            $view->set_display('page');
            $view->exposed_input['field_event_date_value2']['value']['date'] = '2014-01-01';
            $view->execute();
            return $view->preview();*/
            break;
    }
}